[book]
title = "Learn Holochain"
authors = ["Joshua Vial"]
description = "A guide for self-directed study through the open Holochain curriculum"
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
use-default-colors = false
no-section-label = true
smart-punctuation = true
mathjax-support = false
copy-fonts = true
git-repository-url = "https://github.com/CodeWithJV/learn-holochain"
edit-url-template = "https://github.com/CodeWithJV/learn-holochain/edit/main/{path}"
additional-js = ["theme/force-light.js"]
site-url = "/learn-holochain/"
